### ISSUE TITLE
Gulp + Bower

### ISSUE THREAD

**Issue by acacioosorio** [eventos-do-bem/frontend-app#11]
Trazer as tasks necessárias para um Task Runner (Gulp) e gerenciador de dependências (Bower).
Evitando assim problemas com futuros colaboradores e a necessidade de contêineres de software (Docker).

**Comment by juniorb2ss** [comment]
Eu acho válida essa sugestão, realmente tivemos problemas com alguns colaboradores quanto a compatibilidade com outros sistemas operacionais. 

Junto com essa implementação seria interessante efetuar a implementação do `gulp-rev`, para forçar a reescritura do cache.

:+1:

**Comment by guiseek** [comment]
@acacioosorio pode me dar um motivo para usarmos o gulp e bower?
Pergunto isto pois o npm (Node package manager) é um gerenciador de dependências e também um task runner, justamente por isso decidi não usar o gulp & bower, evitando pacotes extras, diminuindo uso de storage e tempo de build

Pra instalação do bower são necessários node / npm, então seu uso não os dispensa.
As tarefas usadas no desenvolvimento estão na seção scripts do package.json (config do npm) como pode ser visto aqui:
https://github.com/eventos-do-bem/frontend-app/blob/master/package.json

Algumas tarefas fazem a concatenação e minificação, e por usar tasks com o próprio npm, ele procura as libs dentro de node_modules, se fôssemos usar bower teria de reescreve-las e nem todos pacotes que estamos usando estão disponíveis no bower, o que também traria transtorno.

Pode me informar qual foi seu problema ao preparar o ambiente? tive um problema sobre precisar criar o diretório dist antes de usar as tarefas npm run prod e npm start
Outro problema que também possa ocorrer, é pela versão do node / npm instalados na sua maquina.

Eu também não estou usando Docker por enquanto...
Sobre o gulp, pode me dizer algum benefício que ele traria?

**Comment by guiseek** [comment]
@juniorb2ss vamos esperar a resposta dele sobre uso do gulp, se houver, usamos o gulp-rev, se não vejo algo parecido para npm scripts.

**Comment by juniorb2ss** [comment]
@guiseek Perfeito ponto colocado! Se não tiver benefício também não compensa trocar, vamos buscar tratar o problema que os colaboradores estão enfrentando, mas antes, precisamos de um retorno do problema.

Sobre o `gulp-rev` se faz necessário sim, pois isso força com exatidão o flush do cache, mesmo que há o `invalidations` o browser em si ou provedor pode efetuar um cache pesado, com o versionamento contornamos ainda mais isso.

**Comment by guiseek** [comment]
@acacioosorio você tem algum domínio sobre webpack?
Vi nele algumas coisas que seriam interessantes e que talvez até pudéssemos remover alguns 📦  utilizados em algumas tarefas, onde ele resolveria e até outras questões que precisaremos futuramente...
Se souber de algo que possa nos ajudar sobre ele, sou todo ouvidos 😄 👍
