### ISSUE TITLE
Crop da imagem do perfil

### ISSUE THREAD

**Issue by mica-eu** [eventos-do-bem/frontend-app#13]
Implementar crop da imagem do perfil quando o usuário quiser adicionar ou trocar a foto. Isso ajudará a evitar problemas como a issue #2 .

**Comment by guiseek** [comment]
@micaelsouza tudo bem? obrigado pela contribuição no projeto! 😄  👍 

Uma questão que gostaria de ver contigo é sobre o atributo `area-type`. Pois um dos requisitos do projeto é também suportar crop em diferentes tamanhos de width e height (no caso, em retângulo) e pelo que vi, a lib usada suporta apenas `circle|square`.
Dando uma olhada nas issues vi sugestões sobre a [ngImgCropFullExtended](https://github.com/CrackerakiUA/ngImgCropFullExtended/), que agora é [ui-cropper](https://github.com/CrackerakiUA/ui-cropper), contudo ainda tive uns problemas de retrocompatibilidade com a lib atual em warnings de `size` e `ColorThief`...

Você já teve algum case assim onde usou alguma solução parecida?

**Comment by mica-eu** [comment]
Fala @guiseek, Então...
Eu tava vendo isso e também reparei que a lib que eu usei tem essa limitação. Eu vou dar uma olhada nessa que você citou e, pelo jeito, vamos refazer a diretiva que eu criei utilizando essa lib que você falou. Quanto à sua pergunta sobre o ```area-type```, eu ainda não tinha feito nada utilizando crop de imagem e angularjs antes.
