### ISSUE TITLE
Arrumar Avatar e thumbnail

### ISSUE THREAD

**Issue by nandagiannini** [eventos-do-bem/frontend-app#2]
- [ ] Avatar está achatado, quando deveria estar perfeitamente circular - por exemplo: https://www.eventosdobem.com.br/#/evento/bloco-da-vaquinha-para-roraima-derrubando-muros
- [ ] colocar a border do avatar para a cor #ccc
- [ ] Arrumar a thumbnail do card da página explore novas causas ( https://www.eventosdobem.com.br/#/evento/explore) para não ficar cortada como está. vide: 
![screen shot 2017-02-26 at 18 12 57](https://cloud.githubusercontent.com/assets/6574894/23343775/75f22d18-fc4f-11e6-99e3-56a8bfd314c8.png)
![screen shot 2017-02-26 at 18 13 03](https://cloud.githubusercontent.com/assets/6574894/23343776/76172672-fc4f-11e6-865e-d9ae2c9dd472.png)

**Comment by juniorb2ss** [comment]
Close #6

**Comment by juniorb2ss** [comment]
Fixed #6

**Comment by juniorb2ss** [comment]
Closes #6
