### ISSUE TITLE
Confirmar email válido - cadastro via facebook

### ISSUE THREAD

**Issue by nandagiannini** [eventos-do-bem/frontend-app#4]
Conforme  está o layout de referência do produto final: 
![tela-confirma-facebook](https://cloud.githubusercontent.com/assets/6574894/23377618/7785e9a6-fd0f-11e6-8830-15ebe59ab7e4.jpg)

Quando for efetivado o cadastro do usuário pelo facebook, abrir em seguida após o login uma pop up ---> Escrita:  "Olá NOME DO USUÁRIO , por favor confirme seu email para enviarmos informações como recibos de doações e avisos importante relativos à suas campanhas."

Abaixo aparecer um input com o email da pessoa que está cadastrado no facebook já neste input, assim se a pessoa quiser alterar é só editar as informações do input e clicar logo abaixo do input no botão escrito "confirmar email".

Ao ser clicado esse botão atualiza no registro do usuário o email submetido na popup.

O botão está na cor:#249ff6

**Comment by juniorb2ss** [comment]
@nandagiannini atualize com o layout correto previsto.

**Comment by nandagiannini** [comment]
não é esse @juniorb2ss ?
